### ISSUE TITLE
airbods lag sound in games only

### ISSUE THREAD

**Issue by kareem966** [NusantaraROM-Devices/DeviceChangelogs#1]
is:open is:issue author:@me  airbods has a delay in sound just in games. in miui i was play pubg without any delay or lag in sound but in nusantara  the sound was so late compared with action in game... i wish that will fix

**Comment by andrraa** [comment]
Which device and where the log ?

**Comment by kareem966** [comment]
i don't know how i attach the log
my device is redmi note 7 lavonder

**Comment by goodmeow** [comment]
Owner not sending logs so nothing to do.
