### ISSUE TITLE
Wake up issue

### ISSUE THREAD

**Issue by saifo1234** [NusantaraROM-Devices/DeviceChangelogs#2]
When leave the mobile for 5 min and tap on power button to wake up the device it open in low brightness and return to the usual brightness

**Comment by saifo1234** [comment]
Realms 5 pro

**Comment by 703joko** [comment]
Please try to change other kernel, and lets see

**Comment by saifo1234** [comment]
I try to change kernel the same

**Comment by goodmeow** [comment]
Owner doesn't provide logs, so nothing to do
