### ISSUE TITLE
Sluggish Touch Response While Recording

### ISSUE THREAD

**Issue by ghost** [NusantaraROM-Devices/DeviceChangelogs#3]
When I Play PUBGM, it runs smoothly and performance is great. But As I Start Using Screen Recorder. There Is Delay in Touch Response and Screen is Sluggish...
Please Fix It ASAP.

**Comment by goodmeow** [comment]
@g2lxwolf Device?

**Comment by ghost** [comment]
> @g2lxwolf Device?

Vayu POCO X3 PRO

**Comment by goodmeow** [comment]
Owner doesn't provide logs, so nothing to do
