### ISSUE TITLE
Display Laggy And Delayed While Recording

### ISSUE THREAD

**Issue by ghost** [NusantaraROM-Devices/DeviceChangelogs#4]
Sir, I've already informed this issue and would like to inform again. Please fix this issue for POCO X3 PRO (vayu). While I Record My Screen While Playing Game, My Game Becomes Choppy and Touch Response Lags Alot... Kindly Tell Me When is the next version rolling out with the fix? This Issue Wasn't There In The Last Update. It Started After The Latest Update.

**Comment by Rafiester** [comment]
@g2lxwolf Halah

**Comment by goodmeow** [comment]
Owner doesn't provide logs, so nothing to do
