### ISSUE TITLE
[Platina] Sudden bricks and cannot open developer mode

### ISSUE THREAD

**Issue by hafizdkren** [NusantaraROM-Devices/DeviceChangelogs#5]
My device got bricked, wanna open developer mode but it can't. trying to fixing fastboot but not detected, recovery also got impact with unable to do anything.

**Comment by Aoihara** [comment]
@hafizdkren Before your phone bricked, are you installing some modules, changing kernel, flashing wrong firmware, or some mods on your device?
Cos this is the first time we got that bricked issue. Thanks

**Comment by Aoihara** [comment]
No reply till now, so case closed.
